package wired

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strings"
	"text/template"
)

// Emit writes the generated Go source for spec to w. The output is gofmt'd.
func Emit(w io.Writer, spec *Spec) error {
	if err := spec.Validate(); err != nil {
		return err
	}

	data, err := newTemplateData(spec)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := emitTemplate.Execute(&buf, data); err != nil {
		return fmt.Errorf("wired: render template: %w", err)
	}
	formatted, ferr := format.Source(buf.Bytes())
	if ferr != nil {
		_, _ = w.Write(buf.Bytes())
		return fmt.Errorf("wired: format generated source: %w", ferr)
	}
	_, err = w.Write(formatted)
	return err
}

type templateData struct {
	PkgName    string
	Imports    []ImportSpec
	Injector   InjectorSpec
	Providers  []renderedProvider
	HasErrors  bool
	RootVar    string
	NeedsError bool
	HasRoot    bool
}

type renderedProvider struct {
	VarName      string
	Call         string
	ReturnsError bool
}

func newTemplateData(spec *Spec) (templateData, error) {
	if len(spec.Providers) == 0 {
		return templateData{}, fmt.Errorf("wired: spec has no providers")
	}
	providers := make([]renderedProvider, 0, len(spec.Providers))
	for _, p := range spec.Providers {
		providers = append(providers, renderedProvider{
			VarName:      p.VarName,
			Call:         fmt.Sprintf("%s(%s)", p.FuncRef, strings.Join(p.DepVars, ", ")),
			ReturnsError: p.ReturnsError,
		})
	}

	needsError := false
	for _, r := range spec.Injector.Results {
		if r.Type == "error" {
			needsError = true
			break
		}
	}

	rootVar := spec.RootVar
	if rootVar == "" {
		// No primary return type — fall back to the last provider so a
		// pure side-effects injector still compiles. The trailing return
		// uses _ = rootVar to silence the unused-variable warning.
		rootVar = providers[len(providers)-1].VarName
	}

	return templateData{
		PkgName:    spec.PkgName,
		Imports:    spec.Imports,
		Injector:   spec.Injector,
		Providers:  providers,
		RootVar:    rootVar,
		NeedsError: needsError,
		HasRoot:    spec.RootVar != "",
	}, nil
}

var emitTemplate = template.Must(template.New("wired").Funcs(template.FuncMap{
	"zeroResults": func(results []ParamSpec) string {
		if len(results) == 0 {
			return ""
		}
		parts := make([]string, 0, len(results))
		for _, r := range results {
			if r.Type == "error" {
				continue
			}
			parts = append(parts, zeroValue(r.Type))
		}
		return strings.Join(parts, ", ")
	},
	"params": func(params []ParamSpec) string {
		if len(params) == 0 {
			return ""
		}
		parts := make([]string, len(params))
		for i, p := range params {
			if p.Name != "" {
				parts[i] = fmt.Sprintf("%s %s", p.Name, p.Type)
			} else {
				parts[i] = p.Type
			}
		}
		return strings.Join(parts, ", ")
	},
	"results": func(results []ParamSpec) string {
		if len(results) == 0 {
			return ""
		}
		parts := make([]string, len(results))
		for i, r := range results {
			parts[i] = r.Type
		}
		if len(parts) == 1 {
			return parts[0]
		}
		return "(" + strings.Join(parts, ", ") + ")"
	},
}).Parse(`// Code generated by ligo-cli; DO NOT EDIT.

//go:build !wireinject

package {{ .PkgName }}
{{ if .Imports }}
import (
{{- range .Imports }}
	{{ if .Alias }}{{ .Alias }} {{ end }}"{{ .Path }}"
{{- end }}
)
{{- end }}

func {{ .Injector.Name }}({{ params .Injector.Params }}) {{ results .Injector.Results }} {
{{- range .Providers }}
{{- if .ReturnsError }}
	{{ .VarName }}, err := {{ .Call }}
	if err != nil {
		return {{ if $.NeedsError }}{{ zeroResults $.Injector.Results }}, err{{ else }}{{ zeroResults $.Injector.Results }}{{ end }}
	}
{{- else }}
	{{ .VarName }} := {{ .Call }}
{{- end }}
{{- end }}
{{- if .HasRoot }}
	return {{ .RootVar }}{{ if .NeedsError }}, nil{{ end }}
{{- else }}
	_ = {{ .RootVar }}
	return{{ if .NeedsError }} nil{{ end }}
{{- end }}
}
`))

// zeroValue emits a zero-value placeholder for a result slot. Used when a
// factory returns an error mid-chain and we need to satisfy the signature.
func zeroValue(typ string) string {
	switch {
	case strings.HasPrefix(typ, "*"), strings.HasPrefix(typ, "[]"),
		strings.HasPrefix(typ, "map["), strings.HasPrefix(typ, "chan "),
		strings.HasPrefix(typ, "func"), typ == "any", typ == "interface{}":
		return "nil"
	case typ == "string":
		return `""`
	case typ == "bool":
		return "false"
	}
	// Numeric types and named structs fall back to a zero-value composite.
	return typ + "{}"
}
